name: multiflow
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.8.13
  - pip:
      - adeval==1.1.0
      - efficientnet-pytorch==0.7.1
      - gdown==5.2.0
      - imgaug==0.4.0
      - matplotlib
      - numpy==1.23.4
      - opencv-python==4.8.0.74
      - regex==2023.8.8
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.9.1
      - timm==1.0.14
      - torch==2.0.0
      - torchaudio==2.0.1
      - torchmetrics==1.1.2
      - torchvision
      - tqdm==4.64.1
      - wandb==0.12.21
      - einops==0.8.1
      - ttach==0.0.3
